#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

. /venv/bin/activate

export CELERY_BROKER_URL="${REDIS_URL}"

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python << END
import sys
import time
import psycopg2

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        # First try to connect to postgres database to check if server is up
        conn = psycopg2.connect(
            dbname="postgres",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        conn.close()

        # Now try to connect to our actual database
        try:
            conn = psycopg2.connect(
                dbname="${POSTGRES_DB}",
                user="${POSTGRES_USER}",
                password="${POSTGRES_PASSWORD}",
                host="${POSTGRES_HOST}",
                port="${POSTGRES_PORT}",
            )
            conn.close()
            break
        except psycopg2.OperationalError as e:
            if "does not exist" in str(e):
                # Database doesn't exist, create it
                conn = psycopg2.connect(
                    dbname="postgres",
                    user="${POSTGRES_USER}",
                    password="${POSTGRES_PASSWORD}",
                    host="${POSTGRES_HOST}",
                    port="${POSTGRES_PORT}",
                )
                conn.autocommit = True
                cursor = conn.cursor()
                cursor.execute('CREATE DATABASE "${POSTGRES_DB}"')
                cursor.close()
                conn.close()
                sys.stderr.write("Created database ${POSTGRES_DB}\n")
                break
            else:
                raise

    except psycopg2.OperationalError as error:
        sys.stderr.write("Waiting for PostgreSQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write(f"  This is taking longer than expected. Exception: {error}\n")

    time.sleep(1)
END

>&2 echo 'PostgreSQL is available'

exec "$@"
